[package]
name = "tokenparser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
regex = "1"
lazy_static = "1.4.0"
colors-transform = "0.2.4"
clap = { version = "4.0.19", features = ["derive"] }
