[package]
name = "css_math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
matches = "0.1.10"
test-case = "3.1.0"

