[package]
name = "figtok_tokens"
version = "0.1.0"
edition = "2021"
description = "Utility for handling different token types for Figtok"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
css_math = { version = "1.0.0", path = "../css_math" }
colors-transform = "0.2.4"
convert_case = "0.6.0"
once_cell = "1.16.0"
regex = "1"
serde = "1.0.147"
serde_json = "1.0.87"
serde_derive = "1.0.147"

[dev-dependencies]
test-case = "3.1.0"